### ISSUE TITLE
Error compiling: missing binary operator before token "("

### ISSUE THREAD

**Issue by cweiske** [alemart/opensurge#127]
I tried to compile opensurge on my Debian testing laptop and got an error:
```
$ make -j4
[...]
[  3%] Building C object CMakeFiles/opensurge.dir/src/core/image.c.o
/home/cweiske/compilethings/opensurge/src/core/engine.c:72:37: error: missing binary operator before token "("
   72 | #if !SURGESCRIPT_VERSION_IS_AT_LEAST(SURGESCRIPT_MIN_SUP, SURGESCRIPT_MIN_SUB, SURGESCRIPT_MIN_WIP, 0)
      |                                     ^
make[2]: *** [CMakeFiles/opensurge.dir/build.make:160: CMakeFiles/opensurge.dir/src/core/engine.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/opensurge.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I installed `libsurgescript-dev` and `liballegro5-dev` as build dependencies. cmake is version 3.30.5.

What other information do you need?

**Comment by alemart** [comment]
Hello!

Use libsurgescript 0.6.1. Get it [here](https://github.com/alemart/surgescript).

**Comment by cweiske** [comment]
I indeed have libsurgescript 0.5.4.4-1.1+b2 since it's in the debian repositories.

**Comment by alemart** [comment]
I find it difficult to understand why the Debian Games Team haven't yet included the opensurge package to this day, while other major distributions have had it listed for years. F-Droid has the recently ported Android edition listed as well. On the other hand, Debian users can't play it as readily and find themselves compiling the software and struggling with these technicalities unnecessarily.

Anyway, have fun with the engine!

**Comment by alemart** [comment]
> I find it difficult to understand why the Debian Games Team haven't yet included the opensurge package to this day, while other major distributions have had it listed for years. F-Droid has the recently ported Android edition listed as well. On the other hand, Debian users can't play it as readily and find themselves compiling the software and struggling with these technicalities unnecessarily.

Would someone from @Debian look into it?

**Comment by alemart** [comment]
> > I find it difficult to understand why the Debian Games Team haven't yet included the opensurge package to this day, while other major distributions have had it listed for years. F-Droid has the recently ported Android edition listed as well. On the other hand, Debian users can't play it as readily and find themselves compiling the software and struggling with these technicalities unnecessarily.
> 
> Would someone from @Debian look into it?

Hello, @apoleon! Are you able to provide guidance?

**Comment by apoleon** [comment]
I can only state the obvious, which is true for every free software project. Someone must maintain the software in Debian. A good start would be to subscribe to the debian-mentors mailinglist and learn packaging. See also https://mentors.debian.net/intro-maintainers/
Later, if you feel comfortable and can do that without much hands holding you can ask someone from debian-mentors or the Debian Games team to sponsor your package, meaning to upload it into Debian unstable. Ideally you start with surgescript and upgrade it to the latest upstream release. Then you could finish 

https://salsa.debian.org/games-team/opensurge

The most important thing is, you must be committed to the package. If you won't have the time to maintain it for the next couple of years in Debian, then it's better to to do something else. Hope that helps

**Comment by alemart** [comment]
> I can only state the obvious, which is true for every free software project. Someone must maintain the software in Debian. A good start would be to subscribe to the debian-mentors mailinglist and learn packaging. See also https://mentors.debian.net/intro-maintainers/ Later, if you feel comfortable and can do that without much hands holding you can ask someone from debian-mentors or the Debian Games team to sponsor your package, meaning to upload it into Debian unstable. Ideally you start with surgescript and upgrade it to the latest upstream release. Then you could finish
> 
> https://salsa.debian.org/games-team/opensurge
> 
> The most important thing is, you must be committed to the package. If you won't have the time to maintain it for the next couple of years in Debian, then it's better to to do something else. Hope that helps

Thanks for your fast reply, @apoleon. Even though surgescript is present on Debian stable, opensurge isn't yet available on Debian unstable. I don't know why. I'm the main developer of both, and they go hand in hand.

I asked you the question because I saw that opensurge was uploaded by you to [this repository on salsa.debian.org](https://salsa.debian.org/games-team/opensurge) back in 2020. Do you have the information of why the packaging progress remained stalled for all these years, whereas [surgescript progressed normally](https://salsa.debian.org/games-team/surgescript)?

Hello, @coringao! Can you take a new look at the opensurge packaging process for Debian? If you can't, do you know someone who can? Debian users such as @cweiske find themselves struggling unnecessarily, and packaging the software will certainly benefit them. Thank you!

**Comment by apoleon** [comment]
Back then I tried to help coringao for his first Debian packages. I don't remember why opensurge wasn't uploaded to Debian unstable but I remember that I "sponsored" (Debian term for uploading newcomer packages) surgescript. We always look for dedicated people who are interested to maintain games or general packages for Debian. However history tells us, that most people just try to get something into Debian and then they vanish from existence. If you would like to see opensurge properly maintained in Debian, then we need you! Or someone from the opensurge community who is dedicated and wants to help for the foreseeable future. It is very unlikely that someone from the games team will introduce opensurge to Debian because we are busy maintaining hundreds of games from the past 30 years in our spare time... Sorry for being so blunt, but that's the truth ;-)

**Comment by alemart** [comment]
Hi, @apoleon.

> It is very unlikely that someone from the games team will introduce opensurge to Debian because we are busy maintaining hundreds of games from the past 30 years in our spare time... Sorry for being so blunt, but that's the truth ;-)

Hopefully I'm misinterpreting this message, but if I'm not, I find that this argument is not quite believable, because there really are [new games](https://ftp-master.debian.org/new.html) being introduced to Debian on top of many others being maintained. Forgive me if I'm misunderstanding something, but I searched for _Debian Games Team_, and the page showed new games being introduced to Debian at the present time such as [this](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1085150) - in addition, there are also new game repositories imported to salsa/games-team.

Sadly, based on the tone of this message, I sense that there may be a lack of interest in addressing the problem, despite Debian users experiencing unnecessary difficulties and despite the game being easily available elsewhere for a few years and meeting the DFSG. Hopefully I'm misinterpreting this message and this is just a misunderstanding.

> I don't remember why opensurge wasn't uploaded to Debian unstable but I remember that I "sponsored" (Debian term for uploading newcomer packages) surgescript.

Okay, we both don't have clarity on why progress has been stalled during these five years. Hopefully this situation will change. Thank you for your reply.

> We always look for dedicated people who are interested to maintain games or general packages for Debian. However history tells us, that most people just try to get something into Debian and then they vanish from existence.

Yes, I understand your point.

> If you would like to see opensurge properly maintained in Debian, then we need you! Or someone from the opensurge community who is dedicated and wants to help for the foreseeable future.

I believe that the packaging is in the best interest of Debian users. I think that not having the game listed is a loss for them. I don't win nor lose.

Here is what I'm able to do for Debian users at this present day:

* Alternatives: if you, who are reading this, don't have a lot of technical knowledge, you can download the game from Flathub / Snap Store at the present time. You will have to have an additional runtime, but it's still manageable and it's a distro-agnostic alternative that is up to date. In addition, there are sandboxing limitations to be observed with these alternatives in case you want to play user-made derivative games or make your own. Those are explained in the README (paths).
* Request for help: if you have the necessary knowledge and are able to be of help to other Debian users, please help with this demand. There is a need for help with packaging and maintenance, as pointed out by Markus.
* If you know someone linked to Debian who might be interested in packaging this project, please let them know about this demand.
* I am reaching out to the opensurge community to see if someone who appreciates the project can help with the packaging, as suggested. However, I'm not sure that this will be successful.
* I'm leaving this issue open for some time to see if we can find help from someone who comes across these messages in the future.

If you're able to help Debian users and would like to reach out to me, I can be contacted here on GitHub, on Discord (alemart) or via e-mail (alemartf at g mail). Thank you very much.

**Comment by cweiske** [comment]
I think we should keep this issue to the original problem, and my problem is solved by manually installing the lib in the curent version.

**Comment by alemart** [comment]
> I think we should keep this issue to the original problem, and my problem is solved by manually installing the lib in the curent version.

No problem. I am opening a new issue with a clearer title and referencing this one for the context. Glad to hear that your problem is solved!

Based on [this recent message](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1085150) written by a long-time contributor, I believe that it is not really the case that maintainers are super busy and completely overwhelmed to the point of not adding new games, as the previous message suggests. In reality, I think that the problem is finding a contributor who is able to help. I think that there are people who can help, but they are just unaware of this demand at the moment.

I would like to thank you @apoleon for replying to my messages. Had you not replied, I would have stayed in the dark on what the problem is. Thank you very much.

**Comment by alemart** [comment]
Hi @gusnan. There is a misunderstanding.

> So I find this now, I am the "unhelpful" person who's "super busy", and still package other stuff.

I did not say that.

> I don't appreciate being called out for not working on something which I no longer claim to work on.

I did not call you out, nor do I expect you to work on something which you don't claim to do. I understand that packaging is done by volunteers, just like opensurge and much of free software.

In my post of December 2024, I simply pointed to [a message of October 2024](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1085150) showing that new games were being added at the time.

What I do observe, as a fact and not as a judgement, is that: 1) people with the know-how did not have the willingness to work on the package, and 2) people with the willingness to work on the package lack the know-how to do it.

Hopefully that clears out the misunderstanding. If not, please let me know, and I'll be happy to clarify further.

---

In any case, issue #128 is still open. Is any contributor of the Debian Games Team interested in packaging the software? If so, I'll be glad to help if necessary. If not, is there any reason why, and anything we can do about it? Members of our community lack the know-how, @coringao is no longer active, and yet [there are more users to whom the package would be beneficial](https://www.gamingonlinux.com/2026/01/surge-engine-for-sonic-like-platformers-gets-improved-gamepad-support-and-a-new-audio-system/) ([comment](https://www.gamingonlinux.com/2026/01/surge-engine-for-sonic-like-platformers-gets-improved-gamepad-support-and-a-new-audio-system/?comment_id=289062)). Any thoughts?
