### ISSUE TITLE
Crash when going into main menu twice and then back

### ISSUE THREAD

**Issue by Wuzzy2** [alemart/opensurge#14]
How to make Open Surge 0.5.0 crash:

1. Go into Options
2. Enter the “secret” Debug Mode
3. Select `scenes/main_menu.lev`
4. Go into Options
5. Enter the “secret” Debug Mode
6. Select `scenes/main_menu.lev`
7. Select Exit (You should now be in Debug Mode)
8. Hit Esc (You should now be in Options menu)
9. Select “BACK”

Open Surge will crash (segmentation fault). Surgeception. :D

I don't mind if you actually close this as invalid but this was way too funny to not post. :P

**Comment by alemart** [comment]
This is a known issue: it will crash when there is a duplicate scene on the stack. The only known way to trigger it is via the debug mode, or through some well crafted script. In any case, a nicer error message would be beneficial, rather than letting it crash. Let me know if you can trigger a nicer error message using the latest commit.

PS: ahahaha, Surgeception, I love it!

**Comment by Wuzzy2** [comment]
I can confirm the new error msg appears.

**Comment by alemart** [comment]
Good! Duplicate scenes are unsupported at this time.
