### ISSUE TITLE
Untranslatable strings

### ISSUE THREAD

**Issue by Wuzzy2** [alemart/opensurge#61]
Here's a list of untranslatable strings I found:

* "No joysticks have been found!"
* "No way!" (if you press F12 in the main menu)
* "Welcome to Surge Script [version]!"
* Editor entity names
* Level names

**Comment by alemart** [comment]
Thank you for calling attention to these matters.

Level names are indeed not translatable by design.

Editor entity names are specified in SurgeScript files as object names. New entities can be created at any time, by any user. These names are only relevant to level designers and modders. Translating them could cause lots of confusion.

Some messages, such as "No joysticks have been found" and others, are implemented using an internal error mechanism of the engine. These messages work across multiple scenes, but are rendered using an internal font with no ASCII support. This is a current limitation.

"Welcome to SurgeScript" is just a test message informing users about the version of the compiled SurgeScript runtime. While it's possible to make it translatable, it would be of little use.
